name: whats_new_feature
description: Show whats new feature in the latest update
version: 0.0.3
homepage: https://github.com/walid-ashik/whats_new_feature
maintainer: Walid Ashik(@walidashik)

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^4.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0